version: '3.7'

volumes:
  pictures:

services:
  frontend:
    build: frontend/docker
    environment:
      API_URL: /entries
    ports:
      - "80:80"
    volumes:
      - pictures:/usr/share/nginx/html/pictures
      - ./conf:/etc/nginx/conf.d
    links:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/backend-1.0-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres,local,file
      GUESTBOOK_PICTURES_LOCAL_URLPREFIX: "http://localhost/pictures"
      GUESTBOOK_PICTURES_LOCAL_FILEPATH: "/pictures/"
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: hunter2
    volumes:
      - pictures:/pictures
    links:
      - db

  db:
    build: database
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: hunter2
